### ISSUE TITLE
Refactor presets.py into Organization and separate visualization file

### ISSUE THREAD

**Issue by alexjps1** [uoclass/tdxplot#1]
Refactor per_week() and run_year_report() into methods in the Organization class, namely per_week() and per_building()

**Comment by ericedwards02** [comment]
https://github.com/uoclass/tdxplot/commit/7e0897d475175da81620889bfef1a417fbc46084

per_week() has been refactored, still need to look at calculating proper start date.

**Comment by alexjps1** [comment]
https://github.com/uoclass/tdxplot/commit/5ce6daebe0b9d89aff2e07e85833b6fda4245681 When a term start date is not specified by user, it is now calculated using the date of the earliest ticket.

**Comment by alexjps1** [comment]
https://github.com/uoclass/tdxplot/commit/814cdf980af60851170c16d2046cb9a6ae61b405 Refactored `run_year_report()` from `preset.py` into `Organization.per_building()` in `organization.py`.

**Comment by alexjps1** [comment]
71add125880443c31025cfb9a3eb0cafca68e7ae All functionality present in `presets.py` has been implemented across other files, culminating with graph visualization in the new `visual.py` file. Closing issue.
