### ISSUE TITLE
Optionally accept a config file in place of flags

### ISSUE THREAD

**Issue by alexjps1** [uoclass/tdxplot#6]
Accept a configuration file with similar (or expanded) information that would normally be passed into the program by the user using flags.

**Comment by ericedwards02** [comment]
This feature has now been implemented! Config files are saved to a JSON, and can also be loaded as such. Users can overwrite the config file with additional arguments.

**Comment by alexjps1** [comment]
fc4a4b7d3256288a99751fafc2269b660769aa1d Unit tests for saving configs
fdeaff85b19f955385ebef7006ca4901ae233b52 Unit tests for loading configs
And done!
